name: Greeting from Mona

on: push

jobs:
  instal-dep:
    name: Installing Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: use npm for package management
        run: npm i
        
  test-app:
    name: Testing
    runs-on: ubuntu-latest
    steps: 
      - name: use jest for testing 
        run: npm runtest_front_lib
